services:
  - type: web
    name: product-server
    runtime: node
    repo: https://github.com/ВАШ_ЛОГИН/НАЗВАНИЕ_РЕПОЗИТОРИЯ
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    branch: main
